# Generated by Django 2.1.4 on 2018-12-12 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2018, 12, 12))),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('choice_text', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2018, 12, 12))),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('total_mark', models.DecimalField(decimal_places=10, max_digits=19)),
                ('max_time', models.TimeField(default=datetime.time(0, 59))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2018, 12, 12))),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('mark', models.DecimalField(decimal_places=10, max_digits=19)),
                ('number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('multi_choice', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('assessments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2018, 12, 12))),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('assessment_score', models.DecimalField(decimal_places=10, max_digits=19)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('assessments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question'),
        ),
    ]
