# Generated by Django 2.1.4 on 2019-01-01 11:57

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20181229_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 1)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 1)),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 1)),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 1)),
        ),
    ]
