# Generated by Django 2.1.4 on 2019-01-25 12:49

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_answer_is_correct_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_choices',
        ),
        migrations.AddField(
            model_name='assessment',
            name='multi_times',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 25)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 25)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 25)),
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='score',
            name='assessment_score',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateField(default=datetime.date(2019, 1, 25)),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(blank=True, default='started', max_length=250),
        ),
    ]
