# Generated by Django 2.1.4 on 2019-01-25 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20190125_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 17, 24, 57, 903346)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 17, 24, 57, 903346)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 17, 24, 57, 903346)),
        ),
        migrations.AlterField(
            model_name='question',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 17, 24, 57, 903346)),
        ),
        migrations.AlterField(
            model_name='score',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
