# Generated by Django 2.1.4 on 2019-01-25 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20190125_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='assessment_score',
            new_name='correct_score',
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 18, 55, 19, 106778)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 18, 55, 19, 106778)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_mark',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 18, 55, 19, 106778)),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 18, 55, 19, 106778)),
        ),
    ]
