# Generated by Django 2.1.4 on 2019-01-29 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20190125_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 13, 50, 52, 236499)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 13, 50, 52, 236499)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 13, 50, 52, 236499)),
        ),
        migrations.AlterField(
            model_name='score',
            name='correct_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 13, 50, 52, 236499)),
        ),
    ]
