# Generated by Django 2.1.4 on 2019-02-18 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20190129_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 2, 18, 12, 17, 23, 489362))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='title',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 12, 17, 23, 489362)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 12, 17, 23, 489362)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 12, 17, 23, 489362)),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 12, 17, 23, 489362)),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='assessment.AssessmentName'),
            preserve_default=False,
        ),
    ]
