# Generated by Django 2.1.4 on 2019-02-18 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20190218_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='assessment_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.AssessmentName'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 17, 53, 19, 364249)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 17, 53, 19, 364249)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.AssessmentName'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentname',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 17, 53, 19, 364249)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 17, 53, 19, 364249)),
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 17, 53, 19, 364249)),
        ),
    ]
